apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
    - name: the-pod
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: "p4ssw0rd"
      volumeMounts:
        - name: db-creds
          mountPath: "/etc/db_creds"
          readOnly: true
  volumes:
    - name: db-creds
      secret:
        secretName: custom-secret