apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.23.0 ()
  labels:
    io.kompose.service: todoapplication
  name: todoapplication
spec:
  type: NodePort
  ports:
    - name: "32500"
      port: 5000
      targetPort: 5000
      nodePort: 32500
  selector:
    io.kompose.service: todoapplication

