apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.23.0 ()
  labels:
    io.kompose.service: todoapplication
  name: todoapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todoapplication
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.23.0 ()
      labels:
        io.kompose.network/lan_network: "true"
        io.kompose.service: todoapplication
    spec:
      containers:
        - image: systemdevformations/todoapplication-postgres
          name: todoapplication
          ports:
            - containerPort: 5000
          resources: {}
      hostname: todo
      restartPolicy: Always
status: {}
