apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvol-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/vote
    server: 164.132.182.36
    readOnly: false