apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: helloworld
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: helloworld
  sourceRepos:
    - '*'
  destinations:
    - namespace: helloworld
      server: https://kubernetes.default.svc
    - namespace: "pr-*"
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"