---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-notes
spec:
  podSelector:
    matchLabels:
      app: notes
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: "true"