kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: development
  name: developer
rules:
- apiGroups: ["apps"]
  resources: ["pods", "replicasets", "deployment"]
  verbs: ["get","watch","list","create", "update","patch","delete"]

