apiVersion: batch/v1
kind: Job
metadata:
  name: a-parallel-job
spec:
  template:
    spec:
      containers:
        - name: a-parallel-job
          image: bash
          command: ["bash", "-c", "sleep $((RANDOM/1024+1)); exit $((RANDON/16384))"]
      restartPolicy: Never
  parallelism: 4


