apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
spec:
  selector:
    matchLabels:
      tier: my-monolith
  replicas: 1
  template:
    metadata:
      labels:
        tier: my-monolith
    spec:
      containers:
        - name: todo-monolith
          image: systemdevformations/todo-monolith:v1
          ports:
            - containerPort: 5000