apiVersion: v1
kind: Service
metadata:
  name: service-monolith
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    tier: my-monolith
  sessionAffinity: None
  type: NodePort

