version: '3'

networks:
  lan_network:
    driver: bridge

services:
  flask:
      hostname: todo
      build: ./flask
      ports:
        - 5000:5000
      volumes:
        - /opt/data:/opt/data
      networks:
        -  lan_network
  sql:
    hostname: sql
    command: tail -f /dev/null
    build: ./sqlite
    networks:
      - lan_network